//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwarmIntelligence.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwarmIntelligence.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///2
        ///242
        ///243
        ///244
        ///241
        ///240
        ///239
        ///238
        ///237
        ///236
        ///235
        ///234
        ///233
        ///232
        ///231
        ///246
        ///245
        ///247
        ///250
        ///251
        ///230
        ///229
        ///228
        ///227
        ///226
        ///225
        ///224
        ///223
        ///222
        ///221
        ///220
        ///219
        ///218
        ///217
        ///216
        ///215
        ///214
        ///213
        ///212
        ///211
        ///210
        ///207
        ///206
        ///205
        ///204
        ///203
        ///202
        ///201
        ///198
        ///197
        ///196
        ///195
        ///194
        ///193
        ///192
        ///191
        ///190
        ///189
        ///188
        ///187
        ///186
        ///185
        ///184
        ///183
        ///182
        ///181
        ///176
        ///180
        ///179
        ///150
        ///178
        ///177
        ///151
        ///152
        ///156
        ///153
        ///155
        ///154
        ///129
        ///130
        ///131
        ///20
        ///21
        ///128
        ///127
        ///126
        ///125
        ///124
        ///123
        ///122
        ///121
        ///120
        ///119
        ///157
        ///158
        ///159
        ///160
        ///175
        ///161
        ///162
        ///163
        ///164
        ///165 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string a280_opt_tour {
            get {
                return ResourceManager.GetString("a280_opt_tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,288,149
        ///2,288,129
        ///3,270,133
        ///4,256,141
        ///5,256,157
        ///6,246,157
        ///7,236,169
        ///8,228,169
        ///9,228,161
        ///10,220,169
        ///11,212,169
        ///12,204,169
        ///13,196,169
        ///14,188,169
        ///15,196,161
        ///16,188,145
        ///17,172,145
        ///18,164,145
        ///19,156,145
        ///20,148,145
        ///21,140,145
        ///22,148,169
        ///23,164,169
        ///24,172,169
        ///25,156,169
        ///26,140,169
        ///27,132,169
        ///28,124,169
        ///29,116,161
        ///30,104,153
        ///31,104,161
        ///32,104,169
        ///33,90,165
        ///34,80,157
        ///35,64,157
        ///36,64,165
        ///37,56,169
        ///38,56,161
        ///39,56,153
        ///40,56,145
        ///41,56,137
        ///42,56,129
        ///43,56,121
        ///44,40,121
        ///45,40 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string a280_tsp_3c {
            get {
                return ResourceManager.GetString("a280_tsp_3c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,36.49,7.49
        ///2,57.06,9.51
        ///3,30.22,48.14
        ///4,5.15,-3.56
        ///5,34.59,-106.37
        ///6,57.12,-2.12
        ///7,16.45,-99.45
        ///8,5.36,-0.10
        ///9,28.56,-13.36
        ///10,8.59,38.48
        ///11,12.50,45.02
        ///12,-34.48,138.38
        ///13,30.23,-9.33
        ///14,56.18,12.51
        ///15,36.40,-4.30
        ///16,40.38,8.17
        ///17,35.11,-3.50
        ///18,41.55,8.48
        ///19,-37.01,174.47
        ///20,38.17,-0.34
        ///21,36.42,3.13
        ///22,36.11,37.14
        ///23,35.14,-101.42
        ///24,31.58,35.59
        ///25,52.18,4.46
        ///26,61.10,-149.59
        ///27,39.57,32.41
        ///28,51.11,4.28
        ///29,17.08,-61.47
        ///30,43.37,13.22
        ///31,29.38,35.01
        ///32,59.39,17.55
        ///33,15. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ali535_tsp_3c {
            get {
                return ResourceManager.GetString("ali535_tsp_3c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///8
        ///38
        ///31
        ///44
        ///18
        ///7
        ///28
        ///6
        ///37
        ///19
        ///27
        ///17
        ///43
        ///30
        ///36
        ///46
        ///33
        ///20
        ///47
        ///21
        ///32
        ///39
        ///48
        ///5
        ///42
        ///24
        ///10
        ///45
        ///35
        ///4
        ///26
        ///2
        ///29
        ///34
        ///41
        ///16
        ///22
        ///3
        ///23
        ///14
        ///25
        ///13
        ///11
        ///12
        ///15
        ///40
        ///9.
        /// </summary>
        internal static string att48_opt_tour {
            get {
                return ResourceManager.GetString("att48_opt_tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,6734,1453
        ///2,2233,10
        ///3,5530,1424
        ///4,401,841
        ///5,3082,1644
        ///6,7608,4458
        ///7,7573,3716
        ///8,7265,1268
        ///9,6898,1885
        ///10,1112,2049
        ///11,5468,2606
        ///12,5989,2873
        ///13,4706,2674
        ///14,4612,2035
        ///15,6347,2683
        ///16,6107,669
        ///17,7611,5184
        ///18,7462,3590
        ///19,7732,4723
        ///20,5900,3561
        ///21,4483,3369
        ///22,6101,1110
        ///23,5199,2182
        ///24,1633,2809
        ///25,4307,2322
        ///26,675,1006
        ///27,7555,4819
        ///28,7541,3981
        ///29,3177,756
        ///30,7352,4506
        ///31,7545,2801
        ///32,3245,3305
        ///33,6426,3173
        ///34,4608,1198
        ///35,23,2216
        ///36,7248,3779
        ///37,7762,4595
        ///38,7392,2244 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string att48_tsp_3c {
            get {
                return ResourceManager.GetString("att48_tsp_3c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,7810,6053
        ///2,7798,5709
        ///3,7264,5575
        ///4,7324,5560
        ///5,7547,5503
        ///6,7744,5476
        ///7,7821,5457
        ///8,7883,5408
        ///9,7874,5405
        ///10,7927,5365
        ///11,7848,5358
        ///12,7802,5317
        ///13,7962,5287
        ///14,7913,5280
        ///15,7724,5210
        ///16,7503,5191
        ///17,7759,5143
        ///18,7890,5130
        ///19,7254,5129
        ///20,7790,5038
        ///21,7142,5032
        ///22,7606,5009
        ///23,7772,4989
        ///24,7744,4933
        ///25,7846,4923
        ///26,7622,4917
        ///27,6937,4917
        ///28,7576,4915
        ///29,7783,4912
        ///30,7716,4909
        ///31,7295,4887
        ///32,7777,4869
        ///33,7700,4854
        ///34,7726,4833
        ///35,7702,4815
        ///36,7583,4813
        ///37,7654,4795
        ///38, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string att532_tsp_3c {
            get {
                return ResourceManager.GetString("att532_tsp_3c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///28
        ///6
        ///12
        ///9
        ///26
        ///3
        ///29
        ///5
        ///21
        ///2
        ///20
        ///10
        ///4
        ///15
        ///18
        ///14
        ///17
        ///22
        ///11
        ///19
        ///25
        ///7
        ///23
        ///8
        ///27
        ///16
        ///13
        ///24.
        /// </summary>
        internal static string bayg29_opt_tour {
            get {
                return ResourceManager.GetString("bayg29_opt_tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,1150.0,1760.0
        ///2,630.0,1660.0
        ///3,40.0,2090.0
        ///4,750.0,1100.0
        ///5,750.0,2030.0
        ///6,1030.0,2070.0
        ///7,1650.0,650.0
        ///8,1490.0,1630.0
        ///9,790.0,2260.0
        ///10,710.0,1310.0
        ///11,840.0,550.0
        ///12,1170.0,2300.0
        ///13,970.0,1340.0
        ///14,510.0,700.0
        ///15,750.0,900.0
        ///16,1280.0,1200.0
        ///17,230.0,590.0
        ///18,460.0,860.0
        ///19,1040.0,950.0
        ///20,590.0,1390.0
        ///21,830.0,1770.0
        ///22,490.0,500.0
        ///23,1840.0,1240.0
        ///24,1260.0,1500.0
        ///25,1280.0,790.0
        ///26,490.0,2130.0
        ///27,1460.0,1420.0
        ///28,1260.0,1910.0
        ///29,360.0,1980.0.
        /// </summary>
        internal static string bayg29_tsp_3c {
            get {
                return ResourceManager.GetString("bayg29_tsp_3c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,97,205,139,86,60,220,65,111,115,227,95,82,225,168,103,266,205,149,120,58,257,152,52,180,136,82,34,145
        ///97,0,129,103,71,105,258,154,112,65,204,150,87,176,137,142,204,148,148,49,41,211,226,116,197,89,153,124,74
        ///205,129,0,219,125,175,386,269,134,184,313,201,215,267,248,271,274,236,272,160,151,300,350,239,322,78,276,220,60
        ///139,103,219,0,167,182,180,162,208,39,102,227,60,86,34,96,129,69,58,60,120,119,192,114,110,192,136,173,173
        ///86,71,125,167,0,51,296,150,42,131,268,88,131,245,201,175,275,218,202,119,50,281, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bayg29_tsp_fdm {
            get {
                return ResourceManager.GetString("bayg29_tsp_fdm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///28
        ///6
        ///12
        ///9
        ///5
        ///26
        ///29
        ///3
        ///2
        ///20
        ///10
        ///4
        ///15
        ///18
        ///17
        ///14
        ///22
        ///11
        ///19
        ///25
        ///7
        ///23
        ///27
        ///8
        ///24
        ///16
        ///13
        ///21.
        /// </summary>
        internal static string bays29_opt_tour {
            get {
                return ResourceManager.GetString("bays29_opt_tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,1150.0,1760.0
        ///2,630.0,1660.0
        ///3,40.0,2090.0
        ///4,750.0,1100.0
        ///5,750.0,2030.0
        ///6,1030.0,2070.0
        ///7,1650.0,650.0
        ///8,1490.0,1630.0
        ///9,790.0,2260.0
        ///10,710.0,1310.0
        ///11,840.0,550.0
        ///12,1170.0,2300.0
        ///13,970.0,1340.0
        ///14,510.0,700.0
        ///15,750.0,900.0
        ///16,1280.0,1200.0
        ///17,230.0,590.0
        ///18,460.0,860.0
        ///19,1040.0,950.0
        ///20,590.0,1390.0
        ///21,830.0,1770.0
        ///22,490.0,500.0
        ///23,1840.0,1240.0
        ///24,1260.0,1500.0
        ///25,1280.0,790.0
        ///26,490.0,2130.0
        ///27,1460.0,1420.0
        ///28,1260.0,1910.0
        ///29,360.0,1980.0.
        /// </summary>
        internal static string bays29_tsp_3c {
            get {
                return ResourceManager.GetString("bays29_tsp_3c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,107,241,190,124,80,316,76,152,157,283,133,113,297,228,129,348,276,188,150,65,341,184,67,221,169,108,45,167
        ///107,0,148,137,88,127,336,183,134,95,254,180,101,234,175,176,265,199,182,67,42,278,271,146,251,105,191,139,79
        ///241,148,0,374,171,259,509,317,217,232,491,312,280,391,412,349,422,356,355,204,182,435,417,292,424,116,337,273,77
        ///190,137,374,0,202,234,222,192,248,42,117,287,79,107,38,121,152,86,68,70,137,151,239,135,137,242,165,228,205
        ///124,88,171,202,0,61,392,202,46,160,319,112,163,322,240,232,314,287,23 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bays29_tsp_fdm {
            get {
                return ResourceManager.GetString("bays29_tsp_fdm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///49
        ///32
        ///45
        ///19
        ///41
        ///8
        ///9
        ///10
        ///43
        ///33
        ///51
        ///11
        ///52
        ///14
        ///13
        ///47
        ///26
        ///27
        ///28
        ///12
        ///25
        ///4
        ///6
        ///15
        ///5
        ///24
        ///48
        ///38
        ///37
        ///40
        ///39
        ///36
        ///35
        ///34
        ///44
        ///46
        ///16
        ///29
        ///50
        ///20
        ///23
        ///30
        ///2
        ///7
        ///42
        ///21
        ///17
        ///3
        ///18
        ///31
        ///22.
        /// </summary>
        internal static string berlin52_opt_tour {
            get {
                return ResourceManager.GetString("berlin52_opt_tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,565.0,575.0
        ///2,25.0,185.0
        ///3,345.0,750.0
        ///4,945.0,685.0
        ///5,845.0,655.0
        ///6,880.0,660.0
        ///7,25.0,230.0
        ///8,525.0,1000.0
        ///9,580.0,1175.0
        ///10,650.0,1130.0
        ///11,1605.0,620.0,
        ///12,1220.0,580.0
        ///13,1465.0,200.0
        ///14,1530.0,5.0
        ///15,845.0,680.0
        ///16,725.0,370.0
        ///17,145.0,665.0
        ///18,415.0,635.0
        ///19,510.0,875.0,
        ///20,560.0,365.0
        ///21,300.0,465.0
        ///22,520.0,585.0
        ///23,480.0,415.0
        ///24,835.0,625.0
        ///25,975.0,580.0
        ///26,1215.0,245.0
        ///27,1320.0,315.0
        ///28,1250.0,400.0
        ///29,660.0,180.0
        ///30,410.0,250.0
        ///31,420.0,555.0
        ///32,575.0,665.0
        ///3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string berlin52_tsp_3c {
            get {
                return ResourceManager.GetString("berlin52_tsp_3c", resourceCulture);
            }
        }
    }
}
